name: Documentation Publish

on:
  workflow_run:
    workflows: ["Documentation Build"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
        with:
          workflow: docs.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Unzip html archive
        working-directory: docs
        run: |
          OUTDIR=$(awk 'NR==1 { if ($3 ~ /^(latest|PR-[0-9]+|[0-9]+\.[0-9a-zA-Z\.\-]+)$/) print $3 }' monitor_*.txt)
          echo "OUTDIR=$OUTDIR" >> "$GITHUB_ENV"
          unzip legacy-ncs*.zip -d $OUTDIR

      - name: Obtain PR number
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        working-directory: docs
        run: |
          echo "PR=$(cat pr.txt)" >> "$GITHUB_ENV"

      - name: Upload to Azure storage
        working-directory: docs
        env:
          AZCOPY_CONCURRENCY_VALUE: 1024
        run: |
         azcopy cp $OUTDIR "${{ vars.NCS_DOC_STORAGE_URL }}?${{ secrets.NCS_DOC_SAS}}" --recursive=true

      - name: Find Comment
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3
        id: fc
        with:
          issue-number: ${{ env.PR }}
          comment-author: 'github-actions[bot]'
          body-includes: documentation preview

      - name: Create or update comment
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.PR }}
          body-path: docs/comment.txt
          edit-mode: replace
